{ lib, ... }:
{
  # The 'enable' option is automatically generated by flake-fhs
  # resulting in: options.services.web-server.enable

  options.services.web-server = {
    port = lib.mkOption {
      type = lib.types.port;
      default = 8080;
      description = "Port to serve on";
    };

    content = lib.mkOption {
      type = lib.types.str;
      default = "<h1>Hello from Flake FHS!</h1>";
      description = "HTML content to serve";
    };

    openFirewall = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Whether to open the firewall port";
    };
  };
}
